import axios from 'axios';
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';

import TopCards from '../../components/TopCards';
import { AiFillCheckCircle, AiFillCloseCircle } from 'react-icons/ai';
import { MdOutlineExpandMore } from 'react-icons/md';
const DocumentIndex: React.FC = () => {
  const nav = useNavigate();
  const [files, setFiles] = useState([]);
  const setup = async () => {
    const resp = await axios.get('http://localhost:8000/api/upload');
    setFiles(files.concat(resp.data));
  };
  useEffect(() => {
    setup();
  }, []);

  function openModal(id: string): React.MouseEventHandler<HTMLButtonElement> {
    return () => {
      console.log('aqui')
      const modal = document.getElementById(id) as HTMLDialogElement;

      if (modal) {
        modal.show();
      } else {
        console.error("Modal não encontrado");
      }
    };
  }
  return (
    <React.Fragment>

      <title>Adao</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />

      <main className="bg-gray-100 min-h-full min-w-screen m-8">

        <TopCards />
        <div className="flex flex-row">
          <div className="flex flex-col items-center justify-center basis-1/3">
            <div className="mockup-phone">
              <div className="camera"></div>
              <div className="display">
                <div className="artboard artboard-demo phone-1">

                </div>
              </div>
            </div>
            <div className="join join-vertical lg:join-horizontal pt-3">
              <div>
                <button className="btn join-item ml-2">Desligar</button>
                <button className="btn join-item ml-2">Refresh</button>
                <button className="btn join-item ml-2" onClick={openModal('my_modal_1')}>Reiniciar</button>
              </div>
            </div>
            <div className="pt-6">

            </div>
          </div>
          <div className="card w-48 basis-2/3">
            <h2 className="card-title pl-8">iPhone 12 128GB Black </h2>
            <div className="card-body flex flex-row">
              <div className="card h-80 bg-white shadow-xl basis-1/2">
                <div className="flex flex-row p-3 justify-between">

                  <h2 className="card-title pl-4 ">Especificações</h2>
                  <label htmlFor="my_modal_6" className=" "><MdOutlineExpandMore className='h-9 text-primary'/></label>
                </div>
                <div className="card-body pt-0">
                  <div className="overflow-x-auto">
                    <table className="table table-zebra w-full">
                      {/* head */}

                      <tbody>
                        {/* row 1 */}
                        <tr>

                          <td className='font-semibold'>Versão do iOs</td>
                          <td>15.4.1</td>
                          <td></td>

                        </tr>
                        {/* row 2 */}
                        <tr>
                          <td className='font-semibold'>Data de Produção</td>
                          <td>11-08-2021</td>
                          <td> </td>
                          <td> </td>


                        </tr>
                        {/* row 3 */}
                        <tr>
                          <th>EMI</th>
                          <td className='font-semibold'>MDM</td>
                          <td className='font-semibold'>Biometric</td>
                          <td></td>
                        </tr>
                        {/* row 3 */}
                        <tr>
                          <th>IMEI</th>
                          <td >357504274152909</td>
                          <td> </td>
                          <td> </td>
                        </tr>
                      </tbody>
                    </table>
                    
                  </div>
                  

                  {/* Put this part before </body> tag */}
                  <input type="checkbox" id="my_modal_6" className="modal-toggle" />
                  <div className="modal">
                    <div className="modal-box">
                      <div className="overflow-x-auto">
                        <table className="table table-zebra w-full">
                          {/* head */}

                          <tbody>
                            {/* row 1 */}
                            <tr>

                              <td className='font-semibold'>Versão do iOs</td>
                              <td>15.4.1</td>
                              <td></td>

                            </tr>
                            {/* row 2 */}
                            <tr>
                              <td className='font-semibold'>Data de Produção</td>
                              <td>11-08-2021</td>
                              <td> </td>
                              <td> </td>


                            </tr>
                            {/* row 3 */}
                            <tr>
                              <th>EMI</th>
                              <td className='font-semibold'>MDM</td>

                              <td></td>
                            </tr>
                            {/* row 3 */}
                            <tr>
                              <th>IMEI</th>
                              <td >357504274152909</td>
                              <td> </td>
                              <td> </td>
                            </tr>
                            <tr>

                              <td className='font-semibold'>Região</td>
                              <td>Brasil</td>
                              <td></td>

                            </tr>
                            {/* row 2 */}
                            <tr>
                              <td className='font-semibold'>Modelo #</td>
                              <td>MGER3LL/A</td>
                              <td> </td>
                              <td> </td>


                            </tr>
                            {/* row 3 */}
                            <tr>
                              <td className='font-semibold'>Saúde da Bateria</td>
                              <td>88%</td>
                              <td></td>
                            </tr>
                            {/* row 3 */}
                            <tr>
                              <th>Vezes carregado</th>
                              <td >721</td>
                              <td> </td>
                              <td> </td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                      <div className="modal-action">
                        <label htmlFor="my_modal_6" className="btn">Voltar</label>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
              <div className="card h-80 bg-white shadow-xl basis-1/2">
                <div className="flex flex-row p-3">

                  <h2 className="card-title pl-4">Testes</h2>
                </div>
                <div className="card-body pt-0">
                  <div className="overflow-x-auto">
                    <table className="table table-zebra w-full">
                      {/* head */}

                      <tbody>
                        {/* row 1 */}
                        <tr>

                          <td className='font-semibold'>Câmera frontal</td>
                          <td><AiFillCheckCircle className='text-primary'/></td>
                          <td></td>

                        </tr>
                        {/* row 2 */}
                        <tr>
                          <td className='font-semibold'>Câmera traseira</td>
                          <td><AiFillCheckCircle className='text-primary'/></td>
                          <td> </td>
                          <td> </td>


                        </tr>
                        {/* row 3 */}
                        <tr>
                          <td className='font-semibold'>GPS e localização</td>
                          <td><AiFillCheckCircle className='text-primary'/></td>
                          <td></td>
                        </tr>
                        {/* row 3 */}
                        <tr>
                          <th>Sensores de movimento</th>
                          <td><AiFillCloseCircle className='text-red-500'/></td>
                          <td> </td>
                          <td> </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <h2 className="card-title pl-8">Armazenamento</h2>
            <div className=" m-8 card h-80  bg-white shadow-xl basis-2/3 p-4">
              <div className="grid grid-cols-2  gap-4">


                <table className="table table-zebra">
                  {/* head */}

                  <tbody>
                    {/* row 1 */}
                    <tr>
                      <th>Sistema</th>
                      <td><progress className="progress w-56" value={22} max="100"></progress></td>
                      <td>22%</td>

                    </tr>
                    {/* row 2 */}
                    <tr>
                      <th>Aplicativos</th>
                      <td><progress className="progress  w-56" value={37} max="100"></progress></td>
                      <td>37%</td>

                    </tr>
                    {/* row 3 */}
                    <tr>
                      <th>Fotos</th>
                      <td><progress className="progress  w-56" value={15} max="100"></progress></td>
                      <td>15%</td>

                    </tr>
                  </tbody>
                </table>
                <div className="stats bg-primary text-primary-content ml-6">

                  <div className="stat">
                    <div className="stat-title">Memória Utilizada</div>
                    <div className="stat-value text-2xl text-white">29,13 GB</div>
                    <div className="stat-actions">
                      <button className="btn btn-sm btn-success">limpeza</button>
                    </div>
                  </div>

                  <div className="stat">
                    <div className="stat-title font-light">Memória Total</div>
                    <div className="stat-value text-2xl text-white">256,00 GB</div>

                  </div>

                </div>
              </div>

            </div>

          </div>
        </div>

      </main>
    </React.Fragment>
  );
};

export default DocumentIndex;
