import React from 'react';

import TopCards from '../components/TopCards';

import Photos from '../public/icons/photos.svg';
import Store from '../public/icons/appstore.svg';
import Itunes from '../public/icons/iTunes.png';
import Settings from '../public/icons/settings.png';
import Device from '../public/icons/device.png';
import Screen from '../public/screenlock.png';
import Iphone from '../public/icons/iphone14.svg';

const Home = () => {
  return (
    <React.Fragment>
      
        <title>Adao</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
     
      <main className="bg-gray-100 min-h-screen">
        <div className="navbar bg-white">
          <div className="flex-1">
            <a className="btn btn-ghost normal-case text-xl">Adao UI</a>
          </div>
          <div className="flex-none">
            <div className="dropdown dropdown-end">
              <label tabIndex={0} className="btn btn-ghost btn-circle">
                <div className="indicator">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    {/* ...SVG paths here */}
                  </svg>
                  <span className="badge badge-sm indicator-item">8</span>
                </div>
              </label>
              <div tabIndex={0} className="mt-3 z-[1] card card-compact dropdown-content w-52 bg-base-100 shadow"></div>
            </div>
            <div className="dropdown dropdown-end">
              <label tabIndex={0} className="btn btn-ghost btn-circle avatar">
                <div className="w-10 rounded-full">
                  <img src="https://avatars.githubusercontent.com/u/44006588?v=4.jpg" alt="User Avatar" />
                </div>
              </label>
              <ul tabIndex={0} className="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
                <li>
                  <a className="justify-between">
                    Perfil
                    <span className="badge">Novo</span>
                  </a>
                </li>
                <li>
                  <a>Configurações</a>
                </li>
                <li>
                  <a>Sair</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <TopCards />
        <div className="flex flex-row">
          <div className="flex flex-col items-center justify-center basis-1/3">
            <div className="mockup-phone">
              <div className="camera"></div>
              <div className="display">
                <div className="artboard artboard-demo phone-1">
                  
                </div>
              </div>
            </div>
            <div className="join join-vertical lg:join-horizontal">
              <div>
                <button className="btn join-item">Desligar</button>
                <button className="btn join-item">Refresh</button>
                <button className="btn join-item">Reiniciar</button>
              </div>
            </div>
            <div className="pt-6">
              
            </div>
          </div>
          <div className="card w-48 basis-2/3">
            <h2 className="card-title pl-8">Gerenciamento</h2>
            <div className="card-body flex flex-row">
              <div className="card h-80 bg-white shadow-xl basis-1/2">
                <div className="flex flex-row p-3">
                 
                  <h2 className="card-title pl-4">Fotos</h2>
                </div>
                <div className="card-body pt-0">
                  <h2 className="font-semibold text-gray-500">Total</h2>
                  <div className="flex flex-row items-start">
                    <div className="rating rating-xs pr-3">
                      <input type="radio" name="rating-4" className="mask mask-star" />
                      <input type="radio" name="rating-4" className="mask mask-star" />
                      <input type="radio" name="rating-4" className="mask mask-star" />
                      <input type="radio" name="rating-4" className="mask mask-star" checked />
                      <input type="radio" name="rating-4" className="mask mask-star" />
                    </div>
                  
                  </div>
                  <div className="card-actions">
                    <button className="btn btn-default w-full">Limpar fotos semelhantes</button>
                  </div>
                  <div className="card-actions">
                    <button className="btn btn-primary w-full text-white">Exportar fotos</button>
                  </div>
                </div>
              </div>
              <div className="card h-80 bg-white shadow-xl basis-1/2">
                <div className="flex flex-row p-3">
                  
                  <h2 className="card-title pl-4">Aplicativos</h2>
                </div>
                <div className="card-body pt-0">
                  <h2 className="font-semibold text-gray-500">Instalado</h2>
                  <div className="flex flex-row items-start">
                    <div className="rating rating-xs pr-3">
                      <input type="radio" name="rating-4" className="mask mask-star" />
                      <input type="radio" name="rating-4" className="mask mask-star" />
                      <input type="radio" name="rating-4" className="mask mask-star" />
                      <input type="radio" name="rating-4" className="mask mask-star" checked />
                      <input type="radio" name="rating-4" className="mask mask-star" />
                    </div>
                    
                  </div>
                  <div className="card-actions content-end">
                    <button className="btn btn-primary w-full text-white">Gerenciar agora</button>
                  </div>
                </div>
              </div>
            </div>
            <h2 className="card-title pl-8">Acesso Rápido</h2>
            <div className=" m-8 card h-80  bg-white shadow-xl basis-2/3 p-4">
              <div className="grid grid-cols-2 grid-rows-2 gap-4">
                <div className='flex flex-row'>
                 
                  <h2 className="font-semibold text-gray-600 text-center pt-3 pl-2">Tranferir para o iTunes</h2>
                </div>
                <div className='flex flex-row'>
                
                  <h2 className="font-semibold text-gray-600 text-center pt-3 pl-2">Tranferir do iTunes para o dispositivo</h2>
                </div>
                <div className='flex flex-row'>
                 
                  <h2 className="font-semibold text-gray-600 text-center pt-3 pl-2">Controle de acessibilidade do Iphone</h2>
                </div>
                <div className='flex flex-row'>
                
                  <h2 className="font-semibold text-gray-600 text-center pt-3 pl-2">Tela em tempo real</h2>
                </div>
              </div>

            </div>

          </div>
        </div>
        <h2 className="card-title pl-8 pt-5">Armazenamento</h2>
        <div className=" m-8 card h-30  bg-white shadow-xl w-19/20 p-4 flex flex-row">
          <div className="card h-16  bg-gray-100  w-60 text-center p-2">
            <progress className="progress progress-secondary w-56" value='22' max="100"></progress>
            <h2 className=" font-semibold text-gray-500">Sistema</h2>
          </div>
          <div className="card h-16  bg-gray-100  w-60 text-center p-2 ml-5">
            <progress className="progress progress-secondary w-56" value='30' max="100"></progress>
            <h2 className=" font-semibold text-gray-500">Aplicativos</h2>
          </div>
          <div className="card h-16  bg-gray-100  w-60 text-center p-2 ml-5">
            <progress className="progress progress-secondary w-56" value='0' max="100"></progress>
            <h2 className=" font-semibold text-gray-500">Fotos</h2>
          </div>
          <div className="card h-16  bg-gray-100  w-60 text-center p-2 ml-5">
            <progress className="progress progress-secondary w-56" value='0' max="100"></progress>
            <h2 className=" font-semibold text-gray-500">Mídia</h2>
          </div>
          <div className="card h-16  bg-gray-100  w-60 text-center p-2 ml-5">
            <progress className="progress progress-secondary w-56" value='8' max="100"></progress>
            <h2 className=" font-semibold text-gray-500">Outro</h2>
          </div>
          <div className="stats bg-primary text-primary-content ml-6">

            <div className="stat">
              <div className="stat-title">Memória Utilizada</div>
              <div className="stat-value text-2xl text-white">29,13 GB</div>
              <div className="stat-actions">
                <button className="btn btn-sm btn-success">limpeza</button>
              </div>
            </div>

            <div className="stat">
              <div className="stat-title font-light">Memória Total</div>
              <div className="stat-value text-2xl text-white">256,00 GB</div>

            </div>

          </div>

        </div>
      </main>
      </React.Fragment>
  );
};
export default Home;